# docker run --name my-nginx -d -p 8080:80 -v "D:\OneDrive - PSA International\Course -  Containers for Deploying and Scaling Apps\CFDSA-new\day01\nginx:/usr/share/nginx/html:ro" nginx:latest
# docker run --name my-nginx -d -p 8080:80 --network mynet -v "D:\OneDrive - PSA International\Course -  Containers for Deploying and Scaling Apps\CFDSA-new\day01\nginx:/usr/share/nginx/html:ro" nginx:latest
