---
apiVersion: v1
kind: Namespace
metadata:
   name: dov-ns
   labels:
      app: dov
      name: dov-ns
      created-by: ngch
      dept: GIT
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: dov-deploy
   labels:
      app: dov
      name: dov-deploy
      created-by: ngch
      dept: GIT
   namespace: dov-ns
spec: 
   # number of instance
   replicas: 3
   # select pods belonging to this deployment
   selector:
      matchLabels:
         apps: dov
         name: dov-po
   # pod template
   template:
      metadata:
         name: dov-po
         labels:
            apps: dov
            name: dov-po
      spec:
         containers:
         - name: dov-container
           image: stackupiss/dov-bear:v1
           imagePullPolicy: IfNotPresent
           env:
           - name: INSTANCE_NAME
             value: "ngch k8s instance for stackup dov-bear"
           - name: INSTANCE_HASH
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           ports:
           - containerPort: 3000
           livenessProbe:
              httpGet:
                 path: /healthz
                 port: 3000

# kubectl get all -n dov-ns --show-labels
# kubectl scale deploy/dov-deploy -n dov-ns --replicas=1
# kubectl port-forward deploy/dov-deploy -n dov-ns --address='0.0.0.0' 8080:3000