---
apiVersion: v1
kind: Pod
metadata:
   name: dov-po
   labels:
      app: dov
      created-by: ngch
      dept: GIT
   namespace: myns
spec: 
   containers:
   - name: dov-container
     image: chukmunnlee/dov-bear:v4
     imagePullPolicy: IfNotPresent
     env:
     - name: INSTANCE_NAME
       value: "ngch k8s instance"
     ports:
     - containerPort: 3000
     livenessProbe:
        httpGet:
           path: /healthz
           port: 3000
     readinessProbe:
        httpGet:
           path: /healthz
           port: 3000
# kubectl port-forward po/dov-po -n myns --address='0.0.0.0' 8080:3000