---
apiVersion: v1
kind: Service
metadata:
   name: bggdb-svc
   labels:
      name: bggdb-svc
      created-by: ngch
      dept: GIT
   namespace: bggns
spec: 
   type: ClusterIP
   selector:
      name: bgg-database-pod
   ports:
      - name: database-connection
        port: 3306
        targetPort: 3306
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
   name: bggapp-svc
   labels:
      name: bggapp-svc
      created-by: ngch
      dept: GIT
   namespace: bggns
spec: 
   type: LoadBalancer
   selector:
      name: bgg-app-pod
   ports:
      - name: http-connection
        port: 80
        targetPort: 3000
        protocol: TCP

# kubectl port-forward deploy/bgg-app-deployment -n bggns --address='0.0.0.0' 8080:3000
# kubectl port-forward svc/bggapp-svc -n bggns --address='0.0.0.0' 8080:8080