---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: bgg-app-deployment
   labels:
      name: bgg-app-deployment
      created-by: ngch
      dept: GIT
   namespace: bggns
spec: 
   # number of instance
   replicas: 3
   minReadySeconds: 5
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 0
   # select pods belonging to this deployment
   selector:
      matchLabels:
         name: bgg-app-pod
   # pod template
   template:
      metadata:
         name: bgg-app-pod
         labels:
            name: bgg-app-pod
      spec:
         containers:
         - name: bgg-app-container
           image: stackupiss/bgg-backend:v2
           imagePullPolicy: IfNotPresent
           envFrom:
           - configMapRef:
                name: bgg-configmap
           - secretRef:
                name: bgg-secret
           ports:
           - containerPort: 3000
           livenessProbe:
              httpGet:
                 path: /healthz
                 port: 3000
           readinessProbe:
              httpGet:
                 path: /healthz
                 port: 3000

# kubectl apply -f bgg-app-deployment.yaml --record=true
# kubectl -n bggns rollout history deployment/bgg-app-deployment
# kubectl -n bggns rollout status deployment/bgg-app-deployment
# watch kubectl get all,cm,secret -n bggns -owide
# kubectl -n bggns rollout undo deployment/bgg-app-deployment --to-revision=8