---
apiVersion: v1
kind: Secret
metadata:
   name: bgg-secret
   labels:
      name: bgg-secret
      created-by: ngch
      dept: GIT
   namespace: bggns
type: Opaque
data:
   BGG_DB_PASSWORD: Y2hhbmdlaXQ=
