---
apiVersion: v1
kind: Secret
metadata:
   name: minio-secret
   labels:
      name: minio-secret
      created-by: ngch
      dept: GIT
   namespace: minio
type: Opaque
data:
   MINIO_ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: minio-configmap
   labels:
      name: minio-configmap
      created-by: ngch
      dept: GIT
   namespace: minio
data:
   MINIO_ROOT_USER: "root"